name: Docker Image CI

# On a push to the branch named master
on:
  push:
    branches: 
      - master

jobs:
  push-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "my-example-app-project"
          heroku_email: "hantczak8@gmail.com"
          usedocker: true
